#KubeJS Common Properties
#Mon Jun 29 13:46:25 EEST 2026
allowAsyncStreams=true
announceReload=true
creativeModeTabIcon=minecraft\:purple_dye
hideServerScriptErrors=false
ignoreCustomUniqueRecipeIds=false
matchJsonRecipes=true
packmode=
saveDevPropertiesInConfig=false
serverOnly=false
startupErrorGUI=true
startupErrorReportUrl=
