// priority: 100
// Otomatik üretim — elle düzenleme: tools/dedup_mappings.json + python tools/generate_dedup_kubejs.py

global.DEDUP_MAPPINGS = [
    ['tide:carp', 'aquaculture:carp'],
    ['tide:catfish', 'aquaculture:catfish'],
    ['tide:rainbow_trout', 'aquaculture:rainbow_trout'],
    ['tide:smallmouth_bass', 'aquaculture:smallmouth_bass'],
    ['tide:tuna', 'aquaculture:tuna'],
    ['tide:arapaima', 'aquaculture:arapaima'],
    ['tide:bluegill', 'aquaculture:bluegill'],
    ['tide:carp_bucket', 'aquaculture:carp_bucket'],
    ['tide:catfish_bucket', 'aquaculture:catfish_bucket'],
    ['tide:rainbow_trout_bucket', 'aquaculture:rainbow_trout_bucket'],
    ['tide:smallmouth_bass_bucket', 'aquaculture:smallmouth_bass_bucket'],
    ['tide:tuna_bucket', 'aquaculture:tuna_bucket'],
    ['tide:arapaima_bucket', 'aquaculture:arapaima_bucket'],
    ['tide:bluegill_bucket', 'aquaculture:bluegill_bucket'],
    ['tide:devils_hole_pupfish_bucket', 'alexsmobs:devils_hole_pupfish_bucket'],
    ['tide:iron_fishing_rod', 'aquaculture:iron_fishing_rod'],
    ['tide:golden_fishing_rod', 'aquaculture:gold_fishing_rod'],
    ['tide:diamond_fishing_rod', 'aquaculture:diamond_fishing_rod'],
    ['tide:fishing_line', 'aquaculture:fishing_line'],
    ['hybrid_aquatic:tuna', 'aquaculture:tuna'],
    ['hybrid_aquatic:carp', 'aquaculture:carp'],
    ['hybrid_aquatic:goldfish', 'aquaculture:goldfish'],
    ['hybrid_aquatic:piranha', 'aquaculture:piranha'],
    ['tide:coelacanth', 'hybrid_aquatic:coelacanth'],
    ['tide:mackerel', 'hybrid_aquatic:mackerel'],
    ['tide:anglerfish', 'hybrid_aquatic:anglerfish'],
    ['crabbersdelight:clam', 'crittersandcompanions:clam'],
    ['hybrid_aquatic:clam', 'crittersandcompanions:clam'],
    ['croptopia:clam', 'crittersandcompanions:clam'],
    ['crabbersdelight:pearl', 'crittersandcompanions:pearl'],
    ['hybrid_aquatic:pearl', 'crittersandcompanions:pearl'],
    ['hybrid_aquatic:pearl_block', 'crabbersdelight:pearl_block'],
    ['crabbersdelight:coconut', 'beachparty:coconut'],
    ['croptopia:coconut', 'beachparty:coconut'],
    ['hybrid_aquatic:cooked_lobster_tail', 'alexsmobs:cooked_lobster_tail'],
    ['hybrid_aquatic:cooked_crab', 'crabbersdelight:cooked_crab'],
    ['hybrid_aquatic:cooked_shrimp', 'crabbersdelight:cooked_shrimp'],
    ['hybrid_aquatic:shark_tooth', 'alexsmobs:shark_tooth'],
    ['aquaculture:fish_bones', 'alexsmobs:fish_bones'],
    ['crabbersdelight:fish_bones', 'alexsmobs:fish_bones'],
    ['beachparty:message_in_a_bottle', 'aquaculture:message_in_a_bottle'],
    ['hybrid_aquatic:message_in_a_bottle', 'aquaculture:message_in_a_bottle'],
    ['crabbersdelight:palm_log', 'beachparty:palm_log'],
    ['crabbersdelight:palm_wood', 'beachparty:palm_wood'],
    ['crabbersdelight:palm_planks', 'beachparty:palm_planks'],
    ['crabbersdelight:palm_stairs', 'beachparty:palm_stairs'],
    ['crabbersdelight:palm_slab', 'beachparty:palm_slab'],
    ['crabbersdelight:palm_fence', 'beachparty:palm_fence'],
    ['crabbersdelight:palm_fence_gate', 'beachparty:palm_fence_gate'],
    ['crabbersdelight:palm_door', 'beachparty:palm_door'],
    ['crabbersdelight:palm_button', 'beachparty:palm_button'],
    ['crabbersdelight:palm_pressure_plate', 'beachparty:palm_pressure_plate'],
    ['crabbersdelight:palm_leaves', 'beachparty:palm_leaves'],
    ['crabbersdelight:palm_sign', 'beachparty:palm_sign'],
    ['crabbersdelight:palm_hanging_sign', 'beachparty:palm_hanging_sign'],
    ['crabbersdelight:palm_boat', 'beachparty:palm_boat'],
    ['crabbersdelight:palm_chest_boat', 'beachparty:palm_chest_boat'],
    ['crabbersdelight:stripped_palm_log', 'beachparty:stripped_palm_log'],
    ['crabbersdelight:stripped_palm_wood', 'beachparty:stripped_palm_wood'],
    ['crabbersdelight:palm_cabinet', 'beachparty:palm_cabinet'],
    ['alexsmobs:shrimp_fried_rice', 'crabbersdelight:shrimp_fried_rice'],
    ['hybrid_aquatic:blobfish', 'alexsmobs:blobfish'],
    ['hybrid_aquatic:flying_fish', 'alexsmobs:flying_fish'],
    ['hybrid_aquatic:raw_crab', 'crabbersdelight:crab'],
    ['hybrid_aquatic:raw_shrimp', 'crabbersdelight:shrimp'],
    ['hybrid_aquatic:raw_lobster', 'alexsmobs:lobster_tail'],
    ['hybrid_aquatic:raw_lobster_tail', 'alexsmobs:lobster_tail'],
    ['hybrid_aquatic:cooked_lobster', 'alexsmobs:cooked_lobster_tail'],
    ['hybrid_aquatic:cooked_clam', 'crabbersdelight:cooked_clam_meat'],
    ['hybrid_aquatic:cooked_mussel', 'beachparty:cooked_mussel_meat'],
    ['hybrid_aquatic:raw_tentacle', 'crabbersdelight:raw_squid_tentacles'],
    ['hybrid_aquatic:cooked_tentacle', 'crabbersdelight:cooked_squid_tentacles'],
    ['oceansdelight:tentacles', 'crabbersdelight:raw_squid_tentacles'],
    ['oceansdelight:cut_tentacles', 'crabbersdelight:raw_squid_tentacles'],
    ['candlelight:acacia_cabinet', 'farmersdelight:acacia_cabinet'],
    ['candlelight:bamboo_cabinet', 'farmersdelight:bamboo_cabinet'],
    ['candlelight:birch_cabinet', 'farmersdelight:birch_cabinet'],
    ['candlelight:cherry_cabinet', 'farmersdelight:cherry_cabinet'],
    ['candlelight:crimson_cabinet', 'farmersdelight:crimson_cabinet'],
    ['candlelight:dark_oak_cabinet', 'farmersdelight:dark_oak_cabinet'],
    ['candlelight:jungle_cabinet', 'farmersdelight:jungle_cabinet'],
    ['candlelight:mangrove_cabinet', 'farmersdelight:mangrove_cabinet'],
    ['candlelight:oak_cabinet', 'farmersdelight:oak_cabinet'],
    ['candlelight:spruce_cabinet', 'farmersdelight:spruce_cabinet'],
    ['candlelight:warped_cabinet', 'farmersdelight:warped_cabinet'],
    ['candlelight:toast', 'bakery:toast'],
    ['candlelight:tomato_sauce', 'farmersdelight:tomato_sauce'],
    ['candlelight:dough', 'farm_and_charm:dough'],
    ['candlelight:cooking_pot', 'farmersdelight:cooking_pot'],
    ['farm_and_charm:onion', 'farmersdelight:onion'],
    ['croptopia:onion', 'farmersdelight:onion'],
    ['farm_and_charm:tomato', 'farmersdelight:tomato'],
    ['croptopia:tomato', 'farmersdelight:tomato'],
    ['farm_and_charm:tomato_seeds', 'farmersdelight:tomato_seeds'],
    ['croptopia:cabbage', 'farmersdelight:cabbage'],
    ['croptopia:rice', 'farmersdelight:rice'],
    ['croptopia:strawberry', 'farm_and_charm:strawberry'],
    ['croptopia:barley', 'farm_and_charm:barley'],
    ['croptopia:oat', 'farm_and_charm:oat'],
    ['croptopia:flour', 'farm_and_charm:flour'],
    ['croptopia:corn', 'farm_and_charm:corn'],
    ['croptopia:lettuce', 'farm_and_charm:lettuce'],
    ['croptopia:butter', 'farm_and_charm:butter'],
    ['croptopia:hops', 'brewery:hops'],
    ['croptopia:toast', 'bakery:toast'],
    ['croptopia:strawberry_jam', 'bakery:strawberry_jam'],
    ['croptopia:dough', 'farm_and_charm:dough'],
    ['bakery:dough', 'farm_and_charm:dough'],
    ['farm_and_charm:onion_soup', 'farmersdelight:onion_soup'],
    ['croptopia:potato_soup', 'farm_and_charm:potato_soup'],
    ['croptopia:pumpkin_soup', 'farmersdelight:pumpkin_soup'],
    ['croptopia:fruit_salad', 'farmersdelight:fruit_salad'],
    ['croptopia:hamburger', 'farmersdelight:hamburger'],
    ['croptopia:sausage', 'brewery:sausage'],
    ['croptopia:fried_chicken', 'brewery:fried_chicken'],
    ['croptopia:mashed_potatoes', 'brewery:mashed_potatoes'],
    ['croptopia:tuna', 'aquaculture:tuna'],
    ['croptopia:shrimp', 'crabbersdelight:shrimp'],
    ['croptopia:cooked_shrimp', 'crabbersdelight:cooked_shrimp'],
    ['croptopia:crab', 'crabbersdelight:crab'],
    ['croptopia:crab_legs', 'crabbersdelight:crab_legs'],
    ['croptopia:sushi', 'aquaculture:sushi'],
    ['croptopia:fish_and_chips', 'aquaculturedelight:fish_and_chips'],
    ['croptopia:bacon', 'farmersdelight:bacon'],
    ['croptopia:cooked_bacon', 'farmersdelight:cooked_bacon'],
    ['croptopia:beef_stew', 'farmersdelight:beef_stew'],
    ['croptopia:ratatouille', 'farmersdelight:ratatouille'],
    ['croptopia:shepherds_pie', 'farmersdelight:shepherds_pie'],
    ['croptopia:apple_pie', 'farmersdelight:apple_pie'],
    ['croptopia:apple_pie_slice', 'farmersdelight:apple_pie_slice'],
    ['croptopia:milk_bottle', 'farmersdelight:milk_bottle'],
    ['croptopia:melon_juice', 'farmersdelight:melon_juice'],
    ['croptopia:beef_wellington', 'candlelight:beef_wellington'],
    ['croptopia:beetroot_salad', 'candlelight:beetroot_salad'],
    ['croptopia:goulash', 'farm_and_charm:goulash'],
    ['croptopia:mead', 'vinery:mead'],
    ['brewery:rope', 'farmersdelight:rope'],
    ['farm_and_charm:stove', 'farmersdelight:stove'],
    ['farm_and_charm:cooking_pot', 'farmersdelight:cooking_pot'],
    ['farm_and_charm:bacon', 'farmersdelight:bacon'],
    ['farm_and_charm:dog_food', 'farmersdelight:dog_food'],
    ['farm_and_charm:minced_beef', 'farmersdelight:minced_beef'],
    ['farm_and_charm:raw_pasta', 'farmersdelight:raw_pasta'],
    ['farm_and_charm:rotten_tomato', 'farmersdelight:rotten_tomato'],
    ['farm_and_charm:wild_onions', 'farmersdelight:wild_onions'],
    ['farm_and_charm:wild_tomatoes', 'farmersdelight:wild_tomatoes'],
    ['farm_and_charm:wild_carrots', 'farmersdelight:wild_carrots'],
    ['farm_and_charm:wild_potatoes', 'farmersdelight:wild_potatoes'],
    ['farm_and_charm:wild_beetroots', 'farmersdelight:wild_beetroots'],
    ['brewery:dumplings', 'farmersdelight:dumplings'],
    ['vinery:apple_juice', 'croptopia:apple_juice'],
    ['vinery:apple_cider', 'farmersdelight:apple_cider'],
    ['fruitfulfun:cherry', 'croptopia:cherry'],
    ['fruitfulfun:orange', 'croptopia:orange'],
    ['fruitfulfun:lemon', 'croptopia:lemon'],
    ['fruitfulfun:lime', 'croptopia:lime'],
    ['fruitfulfun:grapefruit', 'croptopia:grapefruit'],
    ['fruitfulfun:apple_sapling', 'croptopia:apple_sapling'],
    ['fruitfulfun:cherry_sapling', 'croptopia:cherry_sapling'],
    ['fruitfulfun:orange_sapling', 'croptopia:orange_sapling'],
    ['fruitfulfun:lemon_sapling', 'croptopia:lemon_sapling'],
    ['fruitfulfun:lime_sapling', 'croptopia:lime_sapling'],
    ['fruitfulfun:grapefruit_sapling', 'croptopia:grapefruit_sapling'],
    ['fruitfulfun:apple_leaves', 'vinery:apple_leaves'],
    ['fruitfulfun:ender_candle', 'buzzier_bees:ender_candle'],
    ['croptopia:anchovy', 'tide:anchovy'],
    ['croptopia:sea_lettuce', 'hybrid_aquatic:sea_lettuce'],
    ['hybrid_aquatic:otter_spawn_egg', 'crittersandcompanions:otter_spawn_egg'],
    ['tide:tuna_spawn_egg', 'hybrid_aquatic:tuna_spawn_egg'],
    ['tide:anglerfish_spawn_egg', 'hybrid_aquatic:anglerfish_spawn_egg'],
    ['tide:bull_shark_spawn_egg', 'hybrid_aquatic:bull_shark_spawn_egg'],
    ['tide:carp_spawn_egg', 'hybrid_aquatic:carp_spawn_egg'],
    ['tide:coelacanth_spawn_egg', 'hybrid_aquatic:coelacanth_spawn_egg'],
    ['tide:great_white_shark_spawn_egg', 'hybrid_aquatic:great_white_shark_spawn_egg'],
    ['tide:mackerel_spawn_egg', 'hybrid_aquatic:mackerel_spawn_egg'],
    ['tide:manta_ray_spawn_egg', 'hybrid_aquatic:manta_ray_spawn_egg'],
    ['tide:sand_tiger_shark_spawn_egg', 'hybrid_aquatic:sand_tiger_shark_spawn_egg'],
    ['bakery:apple_pie', 'farmersdelight:apple_pie'],
    ['bakery:apple_pie_slice', 'farmersdelight:apple_pie_slice'],
    ['alexsmobs:banana', 'croptopia:banana'],
    ['vinery:cherry', 'croptopia:cherry'],
    ['create_central_kitchen:chocolate_cake_slice', 'bakery:chocolate_cake_slice'],
    ['croptopia:cooking_pot', 'farmersdelight:cooking_pot'],
    ['create:dough', 'farm_and_charm:dough'],
    ['productivebees:milk_bottle', 'farmersdelight:milk_bottle'],
    ['create_central_kitchen:pumpkin_pie_slice', 'farmersdelight:pumpkin_pie_slice'],
    ['tide:diamond_fishing_rod_cast', 'aquaculture:diamond_fishing_rod_cast'],
    ['tide:iron_fishing_rod_cast', 'aquaculture:iron_fishing_rod_cast'],
    ['geckolib:fertilizer', 'farm_and_charm:fertilizer'],
    ['productivebees:honey_bucket', 'create:honey_bucket'],
    ['the_bumblezone:honey_bucket', 'create:honey_bucket'],
    ['brewery:steam_whistle', 'create:steam_whistle'],
    ['farm_and_charm:chicken_nest', 'farmingforblockheads:chicken_nest'],
    ['farm_and_charm:feeding_trough', 'farmingforblockheads:feeding_trough'],
]

global.DEDUP_REMOVED_RECIPES = [
    'crabbersdelight:lanternfish_barrel',
    'crabbersdelight:lanternfish_from_barrel',
    'crabbersdelight:palm_planks',
    'crabbersdelight:palm_stairs',
    'crabbersdelight:palm_slab',
    'crabbersdelight:palm_fence',
    'crabbersdelight:palm_fence_gate',
    'crabbersdelight:palm_door',
    'crabbersdelight:palm_button',
    'crabbersdelight:palm_pressure_plate',
    'crabbersdelight:palm_sign',
    'crabbersdelight:palm_hanging_sign',
    'crabbersdelight:palm_boat',
    'crabbersdelight:palm_chest_boat',
    'crabbersdelight:palm_wood',
    'crabbersdelight:stripped_palm_wood',
    'crabbersdelight:palm_cabinet',
]

global.DEDUP_REMOVED_OUTPUTS = [
    'tide:iron_fishing_rod',
    'tide:golden_fishing_rod',
    'tide:diamond_fishing_rod',
    'tide:fishing_line',
    'tide:fishing_bobber',
]

global.HIDDEN_ITEMS = [
    'alexsmobs:banana',
    'alexsmobs:shrimp_fried_rice',
    'aquaculture:fish_bones',
    'bakery:apple_pie',
    'bakery:apple_pie_slice',
    'bakery:dough',
    'beachparty:message_in_a_bottle',
    'brewery:dumplings',
    'brewery:rope',
    'brewery:steam_whistle',
    'candlelight:acacia_cabinet',
    'candlelight:bamboo_cabinet',
    'candlelight:birch_cabinet',
    'candlelight:cherry_cabinet',
    'candlelight:cooking_pot',
    'candlelight:crimson_cabinet',
    'candlelight:dark_oak_cabinet',
    'candlelight:dough',
    'candlelight:jungle_cabinet',
    'candlelight:mangrove_cabinet',
    'candlelight:oak_cabinet',
    'candlelight:spruce_cabinet',
    'candlelight:toast',
    'candlelight:tomato_sauce',
    'candlelight:warped_cabinet',
    'crabbersdelight:clam',
    'crabbersdelight:coconut',
    'crabbersdelight:fish_bones',
    'crabbersdelight:lanternfish_barrel',
    'crabbersdelight:palm_boat',
    'crabbersdelight:palm_button',
    'crabbersdelight:palm_cabinet',
    'crabbersdelight:palm_chest_boat',
    'crabbersdelight:palm_door',
    'crabbersdelight:palm_fence',
    'crabbersdelight:palm_fence_gate',
    'crabbersdelight:palm_hanging_sign',
    'crabbersdelight:palm_leaves',
    'crabbersdelight:palm_log',
    'crabbersdelight:palm_planks',
    'crabbersdelight:palm_pressure_plate',
    'crabbersdelight:palm_sign',
    'crabbersdelight:palm_slab',
    'crabbersdelight:palm_stairs',
    'crabbersdelight:palm_wood',
    'crabbersdelight:pearl',
    'crabbersdelight:seashell_1',
    'crabbersdelight:seashell_2',
    'crabbersdelight:seashell_3',
    'crabbersdelight:seashell_4',
    'crabbersdelight:seashell_5',
    'crabbersdelight:seashell_6',
    'crabbersdelight:stripped_palm_log',
    'crabbersdelight:stripped_palm_wood',
    'create:dough',
    'create_central_kitchen:chocolate_cake_slice',
    'create_central_kitchen:pumpkin_pie_slice',
    'croptopia:anchovy',
    'croptopia:apple_pie',
    'croptopia:apple_pie_slice',
    'croptopia:bacon',
    'croptopia:barley',
    'croptopia:beef_stew',
    'croptopia:beef_wellington',
    'croptopia:beetroot_salad',
    'croptopia:butter',
    'croptopia:cabbage',
    'croptopia:clam',
    'croptopia:coconut',
    'croptopia:cooked_bacon',
    'croptopia:cooked_shrimp',
    'croptopia:cooking_pot',
    'croptopia:corn',
    'croptopia:crab',
    'croptopia:crab_legs',
    'croptopia:dough',
    'croptopia:fish_and_chips',
    'croptopia:flour',
    'croptopia:fried_chicken',
    'croptopia:fruit_salad',
    'croptopia:goulash',
    'croptopia:hamburger',
    'croptopia:hops',
    'croptopia:lettuce',
    'croptopia:mashed_potatoes',
    'croptopia:mead',
    'croptopia:melon_juice',
    'croptopia:milk_bottle',
    'croptopia:oat',
    'croptopia:onion',
    'croptopia:potato_soup',
    'croptopia:pumpkin_soup',
    'croptopia:ratatouille',
    'croptopia:rice',
    'croptopia:sausage',
    'croptopia:sea_lettuce',
    'croptopia:shepherds_pie',
    'croptopia:shrimp',
    'croptopia:strawberry',
    'croptopia:strawberry_jam',
    'croptopia:sushi',
    'croptopia:toast',
    'croptopia:tomato',
    'croptopia:tuna',
    'farm_and_charm:bacon',
    'farm_and_charm:chicken_nest',
    'farm_and_charm:cooking_pot',
    'farm_and_charm:dog_food',
    'farm_and_charm:feeding_trough',
    'farm_and_charm:minced_beef',
    'farm_and_charm:onion',
    'farm_and_charm:onion_soup',
    'farm_and_charm:raw_pasta',
    'farm_and_charm:rotten_tomato',
    'farm_and_charm:stove',
    'farm_and_charm:tomato',
    'farm_and_charm:tomato_seeds',
    'farm_and_charm:wild_beetroots',
    'farm_and_charm:wild_carrots',
    'farm_and_charm:wild_onions',
    'farm_and_charm:wild_potatoes',
    'farm_and_charm:wild_tomatoes',
    'fruitfulfun:apple_leaves',
    'fruitfulfun:apple_sapling',
    'fruitfulfun:cherry',
    'fruitfulfun:cherry_sapling',
    'fruitfulfun:ender_candle',
    'fruitfulfun:grapefruit',
    'fruitfulfun:grapefruit_sapling',
    'fruitfulfun:lemon',
    'fruitfulfun:lemon_sapling',
    'fruitfulfun:lime',
    'fruitfulfun:lime_sapling',
    'fruitfulfun:orange',
    'fruitfulfun:orange_sapling',
    'geckolib:fertilizer',
    'hybrid_aquatic:blobfish',
    'hybrid_aquatic:blobfish_spawn_egg',
    'hybrid_aquatic:carp',
    'hybrid_aquatic:clam',
    'hybrid_aquatic:comb_jelly_spawn_egg',
    'hybrid_aquatic:cooked_clam',
    'hybrid_aquatic:cooked_crab',
    'hybrid_aquatic:cooked_lobster',
    'hybrid_aquatic:cooked_lobster_tail',
    'hybrid_aquatic:cooked_mussel',
    'hybrid_aquatic:cooked_shrimp',
    'hybrid_aquatic:cooked_tentacle',
    'hybrid_aquatic:crab',
    'hybrid_aquatic:flying_fish',
    'hybrid_aquatic:flying_fish_spawn_egg',
    'hybrid_aquatic:frilled_shark_spawn_egg',
    'hybrid_aquatic:giant_squid_spawn_egg',
    'hybrid_aquatic:goldfish',
    'hybrid_aquatic:hammerhead_shark_spawn_egg',
    'hybrid_aquatic:lobster',
    'hybrid_aquatic:lobster_spawn_egg',
    'hybrid_aquatic:message_in_a_bottle',
    'hybrid_aquatic:orca_spawn_egg',
    'hybrid_aquatic:otter_spawn_egg',
    'hybrid_aquatic:pearl',
    'hybrid_aquatic:pearl_block',
    'hybrid_aquatic:piranha',
    'hybrid_aquatic:raw_crab',
    'hybrid_aquatic:raw_lobster',
    'hybrid_aquatic:raw_lobster_tail',
    'hybrid_aquatic:raw_shrimp',
    'hybrid_aquatic:raw_tentacle',
    'hybrid_aquatic:shark_tooth',
    'hybrid_aquatic:tuna',
    'oceansdelight:cut_tentacles',
    'oceansdelight:tentacles',
    'productivebees:honey_bucket',
    'productivebees:milk_bottle',
    'the_bumblezone:honey_bucket',
    'tide:anglerfish',
    'tide:anglerfish_spawn_egg',
    'tide:arapaima',
    'tide:arapaima_bucket',
    'tide:arapaima_spawn_egg',
    'tide:bluegill',
    'tide:bluegill_bucket',
    'tide:bluegill_spawn_egg',
    'tide:bull_shark_spawn_egg',
    'tide:carp',
    'tide:carp_bucket',
    'tide:carp_spawn_egg',
    'tide:catfish',
    'tide:catfish_bucket',
    'tide:catfish_spawn_egg',
    'tide:coelacanth',
    'tide:coelacanth_spawn_egg',
    'tide:devils_hole_pupfish_bucket',
    'tide:devils_hole_pupfish_spawn_egg',
    'tide:diamond_fishing_rod',
    'tide:diamond_fishing_rod_cast',
    'tide:fishing_bobber',
    'tide:fishing_line',
    'tide:golden_fishing_rod',
    'tide:great_white_shark_spawn_egg',
    'tide:iron_fishing_rod',
    'tide:iron_fishing_rod_cast',
    'tide:mackerel',
    'tide:mackerel_spawn_egg',
    'tide:manta_ray_spawn_egg',
    'tide:rainbow_trout',
    'tide:rainbow_trout_bucket',
    'tide:rainbow_trout_spawn_egg',
    'tide:sand_tiger_shark_spawn_egg',
    'tide:smallmouth_bass',
    'tide:smallmouth_bass_bucket',
    'tide:smallmouth_bass_spawn_egg',
    'tide:tuna',
    'tide:tuna_bucket',
    'tide:tuna_spawn_egg',
    'vinery:apple_cider',
    'vinery:apple_juice',
    'vinery:cherry',
]

global.TIDE_FISH_ITEMS = [
    'aquaculture:carp',
    'aquaculture:catfish',
    'aquaculture:rainbow_trout',
    'aquaculture:smallmouth_bass',
    'aquaculture:tuna',
    'aquaculture:bluegill',
    'aquaculture:arapaima',
    'aquaculture:piranha',
    'aquaculture:goldfish',
    'aquaculture:jellyfish',
    'aquaculture:minnow',
    'aquaculture:perch',
    'aquaculture:pollock',
    'aquaculture:atlantic_cod',
    'aquaculture:blackfish',
    'aquaculture:atlantic_herring',
    'aquaculture:pacific_halibut',
    'aquaculture:atlantic_halibut',
    'aquaculture:red_grouper',
    'hybrid_aquatic:coelacanth',
    'hybrid_aquatic:mackerel',
    'hybrid_aquatic:anglerfish',
    'alexsmobs:blobfish',
    'alexsmobs:flying_fish',
    'crabbersdelight:crab',
    'crabbersdelight:shrimp',
]

global.FISH_BAITS = [
    'aquaculture:worm',
    'aquaculture:leech',
    'tide:bait',
    'tide:abyss_bait',
    'tide:incandescent_bait',
    'tide:lucky_bait',
    'tide:magnetic_bait',
]

global.TIDE_ROD_ITEMS = [
    'aquaculture:iron_fishing_rod',
    'aquaculture:gold_fishing_rod',
    'aquaculture:diamond_fishing_rod',
    'aquaculture:neptunium_fishing_rod',
]
